<?php
return array (
  'database' =>
  array (
    'driver' => 'pdo_mysql',
    'host' => getenv('DB_HOST') ?: 'mysql',
    'port' => getenv('DB_PORT') ?: '3306',
    'dbname' => getenv('DB_NAME') ?: 'espocrm',
    'user' => getenv('DB_USER') ?: 'espocrm',
    'password' => getenv('DB_PASSWORD') ?: 'espocrm123',
    'charset' => 'utf8mb4',
  ),
  'siteUrl' => getenv('SITE_URL') ?: 'http://localhost:8080',
  'isInstalled' => true,
  'cryptKey' => bin2hex(random_bytes(16)),
  'passwordSalt' => bin2hex(random_bytes(16)),
  'hashSecretKey' => bin2hex(random_bytes(32)),
  'defaultPermissions' => 
  array (
    'user' => 644,
    'group' => 755,
  ),
  'systemUser' => 'www-data',
  'cacheTimestamp' => time(),
  'useCache' => true,
  'recordsPerPage' => 20,
  'recordsPerPageSmall' => 5,
  'recordsPerPageSelect' => 10,
  'applicationName' => 'Kwame Oil and Gas CRM',
  'version' => '8.4.0',
  'timeZone' => 'Africa/Luanda',
  'dateFormat' => 'DD/MM/YYYY',
  'timeFormat' => 'HH:mm',
  'weekStart' => 1,
  'thousandSeparator' => ' ',
  'decimalMark' => ',',
  'exportDelimiter' => ';',
  'currencyList' => 
  array (
    0 => 'AOA',
    1 => 'USD',
    2 => 'EUR',
  ),
  'defaultCurrency' => 'AOA',
  'baseCurrency' => 'AOA',
  'currencyRates' => 
  array (
    'USD' => 1.0,
    'EUR' => 1.0,
  ),
  'outboundEmailIsShared' => true,
  'outboundEmailFromName' => 'Kwame Oil and Gas',
  'outboundEmailFromAddress' => 'noreply@kwameoilandgas.ao',
  'smtpServer' => '',
  'smtpPort' => 587,
  'smtpAuth' => true,
  'smtpSecurity' => 'TLS',
  'smtpUsername' => '',
  'smtpPassword' => '',
  'languageList' => 
  array (
    0 => 'pt_PT',
    1 => 'en_US',
  ),
  'language' => 'pt_PT',
  'logger' => 
  array (
    'path' => 'data/logs/espo.log',
    'level' => 'WARNING',
    'rotation' => true,
    'maxFileNumber' => 30,
    'printTrace' => false,
  ),
  'authenticationMethod' => 'Espo',
  'globalSearchEntityList' => 
  array (
    0 => 'Account',
    1 => 'Contact',
    2 => 'Lead',
    3 => 'Opportunity',
  ),
  'tabList' => 
  array (
    0 => 'Account',
    1 => 'Contact',
    2 => 'Lead',
    3 => 'Opportunity',
    4 => 'Case',
    5 => 'Email',
    6 => 'Calendar',
    7 => 'Meeting',
    8 => 'Call',
    9 => 'Task',
  ),
  'quickCreateList' => 
  array (
    0 => 'Account',
    1 => 'Contact',
    2 => 'Lead',
    3 => 'Opportunity',
    4 => 'Meeting',
    5 => 'Call',
    6 => 'Task',
    7 => 'Case',
  ),
  'exportDisabled' => false,
  'adminNotifications' => true,
  'adminNotificationsNewVersion' => true,
  'adminNotificationsNewExtensionVersion' => true,
  'assignmentEmailNotifications' => false,
  'assignmentEmailNotificationsEntityList' => 
  array (
    0 => 'Lead',
    1 => 'Opportunity',
    2 => 'Task',
    3 => 'Case',
  ),
  'assignmentNotificationsEntityList' => 
  array (
    0 => 'Meeting',
    1 => 'Call',
    2 => 'Task',
    3 => 'Email',
  ),
  'portalStreamEmailNotifications' => true,
  'streamEmailNotificationsEntityList' => 
  array (
    0 => 'Case',
  ),
  'emailKeepParentTeamsEntityList' => 
  array (
    0 => 'Case',
  ),
  'streamEmailNotificationsTypeList' => 
  array (
    0 => 'Post',
    1 => 'Status',
    2 => 'EmailReceived',
  ),
  'b2cMode' => false,
  'restrictedMode' => false,
  'webSocketMessager' => 'ZeroMQ',
  'auth2FA' => false,
  'auth2FAMethodList' => 
  array (
    0 => 'Totp',
  ),
  'auth2FAInPortal' => false,
  'personalEmailMaxPortionSize' => 0,
  'inboundEmailMaxPortionSize' => 0,
  'maxEmailAccountCount' => 2,
  'followCreatedEntities' => false,
  'followCreatedEntityTypeList' => 
  array (
    0 => 'Opportunity',
    1 => 'Case',
  ),
  'emailForceUseExternalClient' => false,
  'textFilterUseContainsForVarchar' => false,
  'scopeColorsDisabled' => false,
  'tabColorsDisabled' => false,
  'tabIconsDisabled' => false,
  'activityList' => 
  array (
    0 => 'Meeting',
    1 => 'Call',
  ),
  'historyList' => 
  array (
    0 => 'Meeting',
    1 => 'Call',
    2 => 'Email',
  ),
  'cleanupJobPeriod' => '1 month',
  'cleanupActionHistoryPeriod' => '15 days',
  'cleanupAuthTokenPeriod' => '1 month',
  'cleanupSubscribers' => true,
  'currencyFormat' => 2,
  'currencyDecimalPlaces' => 2,
  'notifications' => true,
  'notificationsCheckInterval' => 10,
  'popupNotificationsCheckInterval' => 15,
  'maxAttachmentSize' => 256,
  'disableSubmitAfterScript' => true,
  'avatarsDisabled' => false,
  'mentionEmailNotifications' => true,
  'massEmailMaxAttemptCount' => 3,
  'massEmailSiteUrl' => getenv('SITE_URL') ?: 'https://crm.kwameoilandgas.ao',
  'personalEmailMaxPortionSizeImap' => 0,
  'inboundEmailMaxPortionSizeImap' => 0,
  'maxProcessingJobs' => 5,
  'daemonMaxProcessNumber' => 5,
  'daemonInterval' => 10,
  'daemonProcessTimeout' => 36000,
  'cronDisabled' => false,
  'maintenanceMode' => false,
  'useWebSocket' => false,
  'webSocketUrl' => 'ws://localhost:8080',
  'webSocketZeroMQSubscriberDsn' => 'tcp://127.0.0.1:7777',
  'webSocketZeroMQSubmissionDsn' => 'tcp://127.0.0.1:7777',
  'isCustomConfig' => true,
);