services:
  espocrm:
    build: 
      context: .
      dockerfile: Dockerfile.full
    container_name: espocrm-app
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SITE_URL=${SITE_URL:-https://crm.kwameoilandgas.ao}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-espocrm}
      - DB_USER=${DB_USER:-espocrm}
      - DB_PASSWORD=${DB_PASSWORD:-espocrm123}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root123}
    volumes:
      - espocrm_data:/var/www/html/data
      - espocrm_custom:/var/www/html/custom
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  mysql:
    image: mysql:8.0
    container_name: espocrm-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root123}
      - MYSQL_DATABASE=${DB_NAME:-espocrm}
      - MYSQL_USER=${DB_USER:-espocrm}
      - MYSQL_PASSWORD=${DB_PASSWORD:-espocrm123}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=no
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql.sh:/docker-entrypoint-initdb.d/init-mysql.sh:ro
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_allowed_packet=64M
      --innodb_buffer_pool_size=128M
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
      --skip-log-bin
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 120s

volumes:
  mysql_data:
    driver: local
  espocrm_data:
    driver: local
  espocrm_custom:
    driver: local

networks:
  dokploy-network:
    external: true